### ISSUE TITLE
Docker-compose integration

### ISSUE THREAD

**Issue by catalinvr** [egaillardon/jmeter#8]
Hi @egaillardon 

Yesterday I started to run the Jmeter with docker-compose and I found the the entrypoint is not working well. 
In case that you have time, please can you take a look on it?

Here is my compose file:
```
version: '3.7'

services:
  jmeter:
    container_name: jmeter
    image: docker.io/egaillardon/jmeter-plugins
    privileged: true
    entrypoint: jmeter
    volumes:
      - ../c4apitime:/sources
      - ./logs:/logs
      - ./results:/results
    command:
      - '--nongui'
      - '-t/sources/${test_file}'
      - '-l/results/result.jtl'
      - '-j/logs/jmeter.logs'
      - '-LDEBUG'
```

As you can see, it was needed to set the entrypoint directly to `jmeter`.
Also it was needed to remove the space after all params. In my case I was not able to use the long format for command, like --testfile.

Thank you.
